export {
  WPP_READY_POLL_INTERVAL_MS,
  MAX_USER_MESSAGE_LENGTH,
  TYPING_DURATION_MIN_MS,
  TYPING_DURATION_MAX_MS,
  OPEN_PHONE_DELAY_MIN_MS,
  OPEN_PHONE_DELAY_MAX_MS,
  ANTI_SPAM_COOLDOWN_MS,
  STITCHER_WAIT_MS,
} from './app.constants';
